set(_AMENT_PACKAGE_NAME "p73_cc")
set(p73_cc_VERSION "0.0.1")
set(p73_cc_MAINTAINER "piene <piene@todo.todo>")
set(p73_cc_BUILD_DEPENDS "rclcpp" "geometry_msgs" "p73_lib" "p73_msgs" "br_driver")
set(p73_cc_BUILDTOOL_DEPENDS "ament_cmake")
set(p73_cc_BUILD_EXPORT_DEPENDS "rclcpp" "geometry_msgs" "p73_lib" "p73_msgs" "br_driver")
set(p73_cc_BUILDTOOL_EXPORT_DEPENDS )
set(p73_cc_EXEC_DEPENDS "rclpy" "sensor_msgs" "std_msgs" "joy" "launch_ros" "ros2launch" "rclcpp" "geometry_msgs" "p73_lib" "p73_msgs" "br_driver")
set(p73_cc_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(p73_cc_GROUP_DEPENDS )
set(p73_cc_MEMBER_OF_GROUPS )
set(p73_cc_DEPRECATED "")
set(p73_cc_EXPORT_TAGS)
list(APPEND p73_cc_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
