set(_AMENT_PACKAGE_NAME "p73_gui")
set(p73_gui_VERSION "0.0.0")
set(p73_gui_MAINTAINER "yong <jasonshin0537@snu.ac.kr>")
set(p73_gui_BUILD_DEPENDS "rclcpp" "std_msgs" "sensor_msgs" "p73_msgs" "rqt_gui" "rqt_gui_cpp" "qt_gui_cpp" "pluginlib")
set(p73_gui_BUILDTOOL_DEPENDS "ament_cmake")
set(p73_gui_BUILD_EXPORT_DEPENDS "rclcpp" "std_msgs" "sensor_msgs" "p73_msgs" "rqt_gui" "rqt_gui_cpp" "qt_gui_cpp" "pluginlib")
set(p73_gui_BUILDTOOL_EXPORT_DEPENDS )
set(p73_gui_EXEC_DEPENDS "qtbase5-dev" "qtbase5-dev-tools" "qttools5-dev" "qttools5-dev-tools" "rclcpp" "std_msgs" "sensor_msgs" "p73_msgs" "rqt_gui" "rqt_gui_cpp" "qt_gui_cpp" "pluginlib")
set(p73_gui_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(p73_gui_GROUP_DEPENDS )
set(p73_gui_MEMBER_OF_GROUPS )
set(p73_gui_DEPRECATED "")
set(p73_gui_EXPORT_TAGS)
list(APPEND p73_gui_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
list(APPEND p73_gui_EXPORT_TAGS "<rqt_gui plugin=\"plugin.xml\"/>")
