set(_AMENT_PACKAGE_NAME "p73_walker_description")
set(p73_walker_description_VERSION "0.0.0")
set(p73_walker_description_MAINTAINER "syuntoku14 <syuntoku14@todo.todo>")
set(p73_walker_description_BUILD_DEPENDS )
set(p73_walker_description_BUILDTOOL_DEPENDS "ament_cmake")
set(p73_walker_description_BUILD_EXPORT_DEPENDS )
set(p73_walker_description_BUILDTOOL_EXPORT_DEPENDS )
set(p73_walker_description_EXEC_DEPENDS "xacro")
set(p73_walker_description_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(p73_walker_description_GROUP_DEPENDS )
set(p73_walker_description_MEMBER_OF_GROUPS )
set(p73_walker_description_DEPRECATED "")
set(p73_walker_description_EXPORT_TAGS)
list(APPEND p73_walker_description_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
