set(_AMENT_PACKAGE_NAME "p73_msgs")
set(p73_msgs_VERSION "0.0.0")
set(p73_msgs_MAINTAINER "yong <jasonshin0537@snu.ac.kr>")
set(p73_msgs_BUILD_DEPENDS "std_msgs")
set(p73_msgs_BUILDTOOL_DEPENDS "ament_cmake" "rosidl_default_generators")
set(p73_msgs_BUILD_EXPORT_DEPENDS "std_msgs")
set(p73_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(p73_msgs_EXEC_DEPENDS "rosidl_default_runtime" "std_msgs")
set(p73_msgs_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(p73_msgs_GROUP_DEPENDS )
set(p73_msgs_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(p73_msgs_DEPRECATED "")
set(p73_msgs_EXPORT_TAGS)
list(APPEND p73_msgs_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
