set(_AMENT_PACKAGE_NAME "p73_controller")
set(p73_controller_VERSION "0.0.0")
set(p73_controller_MAINTAINER "yong <yong@todo.todo>")
set(p73_controller_BUILD_DEPENDS "rclcpp" "p73_msgs" "p73_lib" "br_driver" "sensor_msgs" "p73_cc")
set(p73_controller_BUILDTOOL_DEPENDS "ament_cmake")
set(p73_controller_BUILD_EXPORT_DEPENDS "rclcpp" "p73_msgs" "p73_lib" "br_driver" "sensor_msgs" "p73_cc")
set(p73_controller_BUILDTOOL_EXPORT_DEPENDS )
set(p73_controller_EXEC_DEPENDS "rclcpp" "p73_msgs" "p73_lib" "br_driver" "sensor_msgs" "p73_cc")
set(p73_controller_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(p73_controller_GROUP_DEPENDS )
set(p73_controller_MEMBER_OF_GROUPS )
set(p73_controller_DEPRECATED "")
set(p73_controller_EXPORT_TAGS)
list(APPEND p73_controller_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
