#!/usr/bin/env python3
"""
P73 GUI launcher script for RQt plugin
"""
import sys
from rqt_gui.main import Main

def main():
    """Launch P73 GUI as RQt plugin"""
    plugin = 'p73_gui/P73Gui'
    main = Main(filename=plugin)
    sys.exit(main.main(standalone=plugin, plugin_argument_provider=None))

if __name__ == '__main__':
    main()

