set(_AMENT_PACKAGE_NAME "p73_lib")
set(p73_lib_VERSION "0.0.0")
set(p73_lib_MAINTAINER "yong <yong@todo.todo>")
set(p73_lib_BUILD_DEPENDS "rclcpp" "p73_msgs" "eigen3_cmake_module" "eigen" "pinocchio" "tf2_eigen" "tf2" "geometry_msgs")
set(p73_lib_BUILDTOOL_DEPENDS "ament_cmake")
set(p73_lib_BUILD_EXPORT_DEPENDS "rclcpp" "p73_msgs" "eigen3_cmake_module" "eigen" "pinocchio" "tf2_eigen" "tf2" "geometry_msgs")
set(p73_lib_BUILDTOOL_EXPORT_DEPENDS )
set(p73_lib_EXEC_DEPENDS "rclcpp" "p73_msgs" "eigen3_cmake_module" "eigen" "pinocchio" "tf2_eigen" "tf2" "geometry_msgs")
set(p73_lib_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(p73_lib_GROUP_DEPENDS )
set(p73_lib_MEMBER_OF_GROUPS )
set(p73_lib_DEPRECATED "")
set(p73_lib_EXPORT_TAGS)
list(APPEND p73_lib_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
