set(_AMENT_PACKAGE_NAME "mjc_ros2")
set(mjc_ros2_VERSION "0.0.0")
set(mjc_ros2_MAINTAINER "yong <yong@todo.todo>")
set(mjc_ros2_BUILD_DEPENDS "rclcpp" "p73_lib")
set(mjc_ros2_BUILDTOOL_DEPENDS "ament_cmake")
set(mjc_ros2_BUILD_EXPORT_DEPENDS "rclcpp" "p73_lib")
set(mjc_ros2_BUILDTOOL_EXPORT_DEPENDS )
set(mjc_ros2_EXEC_DEPENDS "rclcpp" "p73_lib")
set(mjc_ros2_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(mjc_ros2_GROUP_DEPENDS )
set(mjc_ros2_MEMBER_OF_GROUPS )
set(mjc_ros2_DEPRECATED "")
set(mjc_ros2_EXPORT_TAGS)
list(APPEND mjc_ros2_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
